### ISSUE TITLE
canu failed with 'failed to precompute mhap indices.  Made 2 attempts, jobs still failed'.

### ISSUE THREAD

**Issue by igordot** [marbl/canu#106]
I was running canu with some new settings when it failed. Then, I went back to the same exact setting that worked earlier in the day and it still failed. According to `correction/1-overlapper/precompute.1.out` log, this seems to be the source of the error:
```
Dumping reads from 1 to 15547 (inclusive).
Starting mhap precompute.
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/umd/marbl/mhap/main/MhapMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: edu.umd.marbl.mhap.main.MhapMain. Program will exit.
```
That sounds like wrong Java version, but `canu.01.out` told me:
```
-- Detected Java(TM) Runtime Environment '1.8.0_05' (from 'java').
```
That is the same as my previous runs. I didn't change anything. I am using a shared cluster, so it's possible something got changed that I am not aware of, but how can I find out what it was?

**Comment by skoren** [comment]
This is definitely a java version error. There must be a difference between your initial environment where can.01.out is running and the mhap job environment. Are they using different SGE options? You should have a record of how the precompute was submitted in 1-overlapper/precompute.jobSubmit.sh

That said, you can always explicitly specify a java to use rather than using one from your path with the variable java=/full/path/to/java/binary

**Comment by igordot** [comment]
I just repeated and everything worked. Looks like it was some sort of a cluster glitch (even though I tried several times yesterday). I was using "gridOptions=-V" every time, so if one job had java 1.8, it should have been all of them.
