### ISSUE TITLE
Mhap overlap jobs failed, tried 2 times, giving up.

### ISSUE THREAD

**Issue by KSL22** [marbl/canu#1074]
Hi, anybody would help me?
I have a problem with canu. I build a bash file, then I use "qsub" command to submit this task to our server. It always fails "Mhap overlap jobs failed, tried 2 times, giving up." I hava deleted any partial files ([ID].mhap) for the failed jobs and then re-running many times. But still wrong with this problem. 

 **bash file**:
cd 
export JAVA_HOME=xxx/jdk1.8.0_181
export JRE_HOME=xxx/jdk1.8.0_181/jre  
export PATH=xxx/jdk1.8.0_181/bin:$PATH
export PATH=xxx/gcc/4.8.4/bin:$PATH
export PATH=xxx/gnuplot-5.2.0/bin:$PATH
unset PERL5LIB
export PATH=xxx/5.20.3/bin:$PATH

```
xxx/canu-1.7.1/Linux-amd64/bin/canu -nanopore-raw oxford.fasta -p ecoli -d ecoli_oxford genomeSize=4.8m maxMemory=256g 

**log file**
-- Canu 1.7.1
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
--   Li H.
--   Minimap and miniasm: fast mapping and de novo assembly for noisy long sequences.
--   Bioinformatics. 2016 Jul 15;32(14):2103-10.
--   http://doi.org/10.1093/bioinformatics/btw152
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_92' (from '/home/wangxiaoquan/shentingting/var/jdk1.8.0_92/bin/java').
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 32 CPUs and 505 gigabytes of memory.
-- Limited to 256g gigabytes from maxMemory option.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (k-mer counting)
-- Local: cormhap    6 GB   16 CPUs x   2 jobs    12 GB   32 CPUs  (overlap detection with mhap)
-- Local: obtovl     4 GB    8 CPUs x   4 jobs    16 GB   32 CPUs  (overlap detection)
-- Local: utgovl     4 GB    8 CPUs x   4 jobs    16 GB   32 CPUs  (overlap detection)
-- Local: ovb        4 GB    1 CPU  x  32 jobs   128 GB   32 CPUs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x  32 jobs   256 GB   32 CPUs  (overlap store sorting)
-- Local: red        4 GB    4 CPUs x   8 jobs    32 GB   32 CPUs  (read error detection)
-- Local: oea        4 GB    1 CPU  x  32 jobs   128 GB   32 CPUs  (overlap error adjustment)
-- Local: bat       16 GB    4 CPUs x   1 job     16 GB    4 CPUs  (contig construction)
-- Local: gfa        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (GFA alignment and processing)
--
-- Found Nanopore uncorrected reads in the input files.
--
-- Generating assembly 'ecoli' in 'xxx/test/ecoli-oxford'
--
-- Parameters:
--
--  genomeSize        4800000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1920 ( 19.20%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Tue Sep  4 20:31:56 2018 with 24289.913 GB free disk space

    cd .
    /home/wangxiaoquan/wanjunyan/var/canu-1.7.1/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./ecoli.gkpStore.BUILDING \
      ./ecoli.gkpStore.gkp \
    > ./ecoli.gkpStore.BUILDING.err 2>&1

-- Finished on Tue Sep  4 20:32:02 2018 (6 seconds) with 24289.874 GB free disk space
----------------------------------------
--
-- In gatekeeper store './ecoli.gkpStore':
--   Found 20365 reads.
--   Found 140042151 bases (29.17 times coverage).
--
--   Read length histogram (one '*' equals 41.48 reads):
--        0    999      0 
--     1000   1999    706 *****************
--     2000   2999   1682 ****************************************
--     3000   3999   1624 ***************************************
--     4000   4999   1543 *************************************
--     5000   5999   1905 *********************************************
--     6000   6999   2691 ****************************************************************
--     7000   7999   2904 **********************************************************************
--     8000   8999   2609 **************************************************************
--     9000   9999   1946 **********************************************
--    10000  10999   1280 ******************************
--    11000  11999    733 *****************
--    12000  12999    397 *********
--    13000  13999    181 ****
--    14000  14999    109 **
--    15000  15999     38 
--    16000  16999      9 
--    17000  17999      4 
--    18000  18999      2 
--    19000  19999      0 
--    20000  20999      0 
--    21000  21999      0 
--    22000  22999      1 
--    23000  23999      0 
--    24000  24999      0 
--    25000  25999      1 
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Tue Sep  4 20:32:06 2018 with 24289.856 GB free disk space (1 processes; 1 concurrently)

    cd correction/0-mercounts
    ./meryl.sh 1 > ./meryl.000001.out 2>&1

-- Finished on Tue Sep  4 20:32:52 2018 (46 seconds) with 24289.247 GB free disk space
----------------------------------------
-- Meryl finished successfully.
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1  70555151 *******************************************************************--> 0.8655 0.5049
--       2-     2   4917952 ********************************************************************** 0.9259 0.5753
--       3-     4   1399886 *******************                                                    0.9380 0.5965
--       5-     7    905449 ************                                                           0.9466 0.6188
--       8-    11   1612461 **********************                                                 0.9586 0.6683
--      12-    16   1552473 **********************                                                 0.9789 0.7922
--      17-    22    494738 *******                                                                0.9949 0.9293
--      23-    29     52236                                                                        0.9993 0.9785
--      30-    37      9061                                                                        0.9997 0.9851
--      38-    46      4073                                                                        0.9998 0.9870
--      47-    56      2676                                                                        0.9998 0.9881
--      57-    67      1989                                                                        0.9999 0.9891
--      68-    79      2326                                                                        0.9999 0.9900
--      80-    92      2011                                                                        0.9999 0.9912
--      93-   106      1225                                                                        1.0000 0.9924
--     107-   121       636                                                                        1.0000 0.9933
--     122-   137       517                                                                        1.0000 0.9938
--     138-   154       349                                                                        1.0000 0.9942
--     155-   172       166                                                                        1.0000 0.9946
--     173-   191       107                                                                        1.0000 0.9948
--     192-   211        80                                                                        1.0000 0.9949
--     212-   232        60                                                                        1.0000 0.9950
--     233-   254        53                                                                        1.0000 0.9951
--     255-   277        37                                                                        1.0000 0.9952
--     278-   301        33                                                                        1.0000 0.9953
--     302-   326        29                                                                        1.0000 0.9954
--     327-   352        21                                                                        1.0000 0.9954
--     353-   379        27                                                                        1.0000 0.9955
--     380-   407        17                                                                        1.0000 0.9955
--     408-   436        19                                                                        1.0000 0.9956
--     437-   466        14                                                                        1.0000 0.9956
--     467-   497        13                                                                        1.0000 0.9957
--     498-   529        17                                                                        1.0000 0.9957
--     530-   562        20                                                                        1.0000 0.9958
--     563-   596        10                                                                        1.0000 0.9959
--     597-   631        16                                                                        1.0000 0.9959
--     632-   667        10                                                                        1.0000 0.9960
--     668-   704         9                                                                        1.0000 0.9960
--     705-   742         8                                                                        1.0000 0.9961
--     743-   781        11                                                                        1.0000 0.9961
--     782-   821         6                                                                        1.0000 0.9962
--
--       13740 (max occurrences)
--    69181525 (total mers, non-unique)
--    10960962 (distinct mers, non-unique)
--    70555151 (unique mers)
-- For mhap overlapping, set repeat k-mer threshold to 1397.
--
-- Found 139736676 16-mers; 81516113 distinct and 70555151 unique.  Largest count 13740.
--
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=high based on read coverage of 29.
--
-- PARAMETERS: hashes=768, minMatches=2, threshold=0.78
--
-- Given 6 GB, can fit 9000 reads per block.
-- For 4 blocks, set stride to 2 blocks.
-- Logging partitioning to 'correction/1-overlapper/partitioning.log'.
-- Configured 3 mhap precompute jobs.
-- Configured 3 mhap overlap jobs.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Tue Sep  4 20:32:59 2018 with 24289.523 GB free disk space (3 processes; 2 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1

-- Finished on Tue Sep  4 20:39:13 2018 (375 seconds) with 24286.181 GB free disk space
----------------------------------------
-- All 3 mhap precompute jobs finished successfully.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Tue Sep  4 20:39:14 2018 with 24286.166 GB free disk space (3 processes; 2 concurrently)

    cd correction/1-overlapper
    ./mhap.sh 1 > ./mhap.000001.out 2>&1
    ./mhap.sh 2 > ./mhap.000002.out 2>&1
    ./mhap.sh 3 > ./mhap.000003.out 2>&1

-- Finished on Tue Sep  4 20:51:16 2018 (722 seconds) with 24284.927 GB free disk space
----------------------------------------
--
-- Mhap overlap jobs failed, retry.
--   job correction/1-overlapper/results/000001.ovb FAILED.
--   job correction/1-overlapper/results/000002.ovb FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Tue Sep  4 20:51:18 2018 with 24284.913 GB free disk space (2 processes; 2 concurrently)

    cd correction/1-overlapper
    ./mhap.sh 1 > ./mhap.000001.out 2>&1
    ./mhap.sh 2 > ./mhap.000002.out 2>&1

-- Finished on Tue Sep  4 20:53:12 2018 (114 seconds) with 24284.056 GB free disk space
----------------------------------------
--
-- Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000001.ovb FAILED.
--   job correction/1-overlapper/results/000002.ovb FAILED.
--

ABORT:
ABORT: Canu 1.7.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**Comment by skoren** [comment]
What is the output in one of the failed jobs (e.g. ecoli_oxford/correction/1-overlapper/mhap.000001.out)?

**Comment by KSL22** [comment]
Running job 1 based on command line options.
Fetch blocks/000002.dat
Fetch blocks/000003.dat

Running block 000001 in query 000001

Picked up _JAVA_OPTIONS: -Xmx1024m -Xms128m
Running with these settings:
--filter-threshold = 5.0E-6
--help = false
--max-shift = 0.2
--min-olap-length = 500
--min-store-length = 0
--no-rc = false
--no-self = false
--no-tf = false
--num-hashes = 768
--num-min-matches = 2
--num-threads = 16
--ordered-kmer-size = 12
--ordered-sketch-size = 1536
--repeat-idf-scale = 10.0
--repeat-weight = 0.9
--settings = 0
--store-full-id = true
--supress-noise = 0
--threshold = 0.78
--version = false
-f = 
-h = false
-k = 16
-p = 
-q = queries/000001
-s = ./blocks/000001.dat

Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Exception in thread "pool-1-thread-9" Exception in thread "pool-1-thread-1" Exception in thread "pool-1-thread-7" Exception in thread "pool-1-thread-4" Exception in thread "pool-1-thread-11" Exception in thread "pool-1-thread-6" Exception in thread "pool-1-thread-2" Exception in thread "pool-1-thread-15" Exception in thread "pool-1-thread-3" Exception in thread "pool-1-thread-8" java.lang.OutOfMemoryError: Java heap space
	at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
	at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:85)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-11"
Exception in thread "pool-1-thread-12" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-1-thread-5" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-1-thread-14" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-1-thread-16" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-1-thread-13" Exception in thread "pool-1-thread-10" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
	at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:85)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.access$000(SequenceSketchStreamer.java:55)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$1.run(SequenceSketchStreamer.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
	at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:85)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.access$000(SequenceSketchStreamer.java:55)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$1.run(SequenceSketchStreamer.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
	at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:85)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.access$000(SequenceSketchStreamer.java:55)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$1.run(SequenceSketchStreamer.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

**Comment by skoren** [comment]
Canu will request the appropriate memory from the JVM for itself but any JAVA_OPTS will over-rule this request. So if you had a different, lower, setting in JAVA_OPTS that would make it crash. As long as JAVA_OPTS is set to at least 12gb it should be fine (the canu memory request).
