### ISSUE TITLE
Java GC overhead limit, no gridEngine

### ISSUE THREAD

**Issue by libby-natola** [marbl/canu#1620]
Hello!

I'm running Canu snapshot v2.0-development +323 changes (r9816 5b94050c362f3d4ccab0344f595da5331cc01ee5) on a virtual machine with 256g of memory.

I'm attempting the correction step on my reads, which from the report file seem to be ~172X of a 1.3g genome. [RBSA_run1.txt](https://github.com/marbl/canu/files/4195613/RBSA_run1.txt)

Here is the code I used:

```
canu -correct \
-p RBSA_run1 -d RBSA_correct \
genomeSize=1.3g \
useGrid=false \
-pacbio-raw  m64086_200128_204022.subreads.fq
```

The first steps seemed to work fine, but at the cormhap step I'm getting standard error output similar to issues #1087 and #1094. My output files have the following error: java.lang.OutOfMemoryError: GC overhead limit exceeded. I think the problem is maybe that my department's server is having issues with slurm right now so I'm not using a gridEngine. I was able to run the whole pipeline for a genome with much lower coverage using the useGrid=false option, but with this amount of data I think there is not enough memory.  I tried changing the mhap.sh file from -Xmx29491m to -Xmx40g to allocate more memory to the mhap step but that didn't solve the problem. I also tried re-running after deleting the mhap results files as suggested in #1087, and running files individually eg `sh mhap.sh 139`. I also tried allocating more memory with the option `cormhapMemory=252`. It shouldn't be a disk space error as it reports 24623.369 gb free. 

Any ideas? Or is it maybe just that my files are too large for my department's server?

Thanks so much for any ideas anyone has. I'm pretty new to bioinformatics so maybe this is a glaringly obvious fix...

**Comment by skoren** [comment]
I would guess there is some issue with the JVM or virtual machine set up. Is there anything else running on the node or have you exclusively reserved that memory/cpu? What happens when you run just one job by hand (e.g. sh.map.sh 1), the full log and top/memory usage of the system?

**Comment by libby-natola** [comment]
Thanks so much for your reply!

Nothing else is running on the node, and I'm the only one on it. I get the same error when I run just a single job by hand, here is the standard error:

[mank03] 1-overlapper $ sh mhap.sh 000029

Found perl:
   /bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /bin/java
   Picked up _JAVA_OPTIONS: -Xms4g -Xmx4g

Found canu:
   /Linux/bin/canu
   Canu snapshot v2.0-development +323 changes (r9816 5b94050c362f3d4ccab0344f595da5331cc01ee5)

Running job 29 based on command line options.
Fetch blocks/000122.dat
Fetch blocks/000123.dat
Fetch blocks/000124.dat
Fetch blocks/000125.dat
Fetch blocks/000126.dat
Fetch blocks/000127.dat
Fetch blocks/000128.dat
Fetch blocks/000129.dat
Fetch blocks/000130.dat
Fetch blocks/000131.dat
Fetch blocks/000132.dat
Fetch blocks/000133.dat
Fetch blocks/000134.dat
Fetch blocks/000135.dat
Fetch blocks/000136.dat
Fetch blocks/000137.dat
Fetch blocks/000138.dat
Fetch blocks/000139.dat
Fetch blocks/000140.dat
Fetch blocks/000141.dat
Fetch blocks/000142.dat
Fetch blocks/000143.dat
Fetch blocks/000144.dat
Fetch blocks/000145.dat
Fetch blocks/000146.dat
Fetch blocks/000147.dat
Fetch blocks/000148.dat
Fetch blocks/000149.dat
Fetch blocks/000150.dat
Fetch blocks/000151.dat
Fetch blocks/000152.dat
Fetch blocks/000153.dat
Fetch blocks/000154.dat

Running block 000007 in query 000029

Picked up _JAVA_OPTIONS: -Xms4g -Xmx4g
Running with these settings:
--filter-threshold = 1.0E-7
--help = false
--max-shift = 0.2
--min-olap-length = 500
--min-store-length = 0
--no-rc = false
--no-self = true
--no-tf = false
--num-hashes = 256
--num-min-matches = 3
--num-threads = 16
--ordered-kmer-size = 14
--ordered-sketch-size = 1000
--repeat-idf-scale = 10.0
--repeat-weight = 0.9
--settings = 0
--store-full-id = true
--supress-noise = 0
--threshold = 0.8
--version = false
-f = 
-h = false
-k = 16
-p = 
-q = queries/000029
-s = ./blocks/000007.dat

Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Current # sequences loaded and processed from file: 65000...
Current # sequences loaded and processed from file: 70000...
Current # sequences loaded and processed from file: 75000...
Current # sequences loaded and processed from file: 80000...
Current # sequences loaded and processed from file: 85000...
Current # sequences loaded and processed from file: 90000...
Current # sequences loaded and processed from file: 95000...
Current # sequences loaded and processed from file: 100000...
Current # sequences loaded and processed from file: 105000...
Current # sequences loaded and processed from file: 110000...
Current # sequences loaded and processed from file: 115000...
Current # sequences loaded and processed from file: 120000...
Current # sequences loaded and processed from file: 125000...
Current # sequences loaded and processed from file: 130000...
Exception in thread "pool-1-thread-15" Exception in thread "pool-1-thread-9" Exception in thread "pool-1-thread-4" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
	at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:85)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.access$000(SequenceSketchStreamer.java:55)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$1.run(SequenceSketchStreamer.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-6"

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-14" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
	at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:85)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.access$000(SequenceSketchStreamer.java:55)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$1.run(SequenceSketchStreamer.java:196)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-15"
Exception in thread "pool-1-thread-10" Exception in thread "pool-1-thread-16" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-3" Exception in thread "pool-1-thread-8" Exception in thread "pool-1-thread-2" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-11"
Exception in thread "pool-1-thread-11" Exception in thread "pool-1-thread-7" Exception in thread "pool-1-thread-5" Exception in thread "pool-1-thread-1" Exception in thread "pool-1-thread-12" Exception in thread "pool-1-thread-13" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
	at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:85)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.access$000(SequenceSketchStreamer.java:55)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$1.run(SequenceSketchStreamer.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
	at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:85)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.access$000(SequenceSketchStreamer.java:55)
	at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$1.run(SequenceSketchStreamer.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by skoren** [comment]
As I suspected, this is a configuration issue. You have the ```_JAVA_OPTIONS: -Xms4g -Xmx4g``` parameter being set in your environment. This overwrites memory settings on the command line so the JVM is always limited to 4gb, even though MHAP would like to use more. That's why increasing the parameters did not help either. 

You can confirm this behavior using ```java -XX:+PrintFlagsFinal ``` flags. For example:
```
% env |grep _JAVA_OPT
% java -Xmx40g -XX:+PrintFlagsFinal -version |grep MaxHeapSize
uintx MaxHeapSize                              := 42949672960     {product}
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)
```
That is OK since 42949672960 = 40gb as expected, however if you have _JAVA_OPTIONS:
```
%env |grep _JAVA_OPT
_JAVA_OPTIONS=-Xms4g -Xmx4g
% java -Xmx40g -XX:+PrintFlagsFinal -version |grep MaxHeapSize
Picked up _JAVA_OPTIONS: -Xms4g -Xmx4g
    uintx MaxHeapSize                              := 4294967296      {product}
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)
```
Note that 4294967296 is 4gb, not 40 like before.

**Comment by libby-natola** [comment]
It seemed as though my issue was the 2nd, it appears 4294967296  is 4 gb

```
$env |grep _JAVA_OPT
_JAVA_OPTIONS=-Xms4g -Xmx4g
$ java -Xmx40g -XX:+PrintFlagsFinal -version |grep MaxHeapSize
Picked up _JAVA_OPTIONS: -Xms4g -Xmx4g
    uintx MaxHeapSize                              := 4294967296                          {product}
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

```
However, after running the unset _JAVA_OPTS (Which I confirmed with the echo $? command)

```
[mank04] ~ $ unset JAVA_OPTS
[mank04] ~ $ echo $?
0
```
I retried `sh mhap.sh 000029` and got a new error

```
Error: dl failure on line 893
Error: failed /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/amd64/server/libjvm.so, because /Linux/lib/libm.so.6: symbol __get_cpu_features, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```
I checked out line 893 in the mhap.sh and I didn't see any obvious issues, I'm assuming it wasn't a problem there.

**Comment by skoren** [comment]
That's not an mhap issue but a JVM issue, your JVM seems to not be starting up, seems like an incompatibility between the library the JVM was built with and what you have installed. Can you run java -version successfully after unsetting the options?

**Comment by libby-natola** [comment]
No, I get the same error

**Comment by skoren** [comment]
I just noticed in your last comment, you unset JAVA_OPTS not _JAVA_OPTIONS, those aren't the same. I think that might have caused the errors, keep JAVA_OPTS but unset _JAVA_OPTIONS instead.

**Comment by libby-natola** [comment]
Unset _JAVA_OPTIONS was returning a 1 with echo ?$ so I assumed it wasn't working. It seems to run now, but I'm still getting the same error I started getting when I ran the JAVA_OPTS command when I run  anything with java.

**Comment by skoren** [comment]
You have to restore JAVA_OPTS to what it was before you unset it I expect to make java work again. Perhaps log out/in to reset the environment. Then confirm you can run the jvm, unset the _JAVA_OPTIONS and confirm you can request more than 4gb of memory. After all those steps work, try running mhap.sh again.

**Comment by libby-natola** [comment]
Sorry, it took us a while to fix java from me unsetting the settings. Now the java memory is set to 32g it seems to run perfectly. Thanks so much for your help!
