### ISSUE TITLE
canu failed when Starting concurrent execution for mhap.sh

### ISSUE THREAD

**Issue by liuqianhn** [marbl/canu#383]
Hi,

I used "canu gnuplotTested=True java="~/exomeSoftware/java/jdk1.8.0_102/bin/java -Xmx1G " useGrid=0 -p ecoli -d ecoli-canu genomeSize=4.8m -pacbio-raw ./ecoli/p6.25x.fastq" to run canu. 

However, I obtained the error below. Anyone can help me to fix this? Thanks.
```
-- Canu v1.4 (+112 commits) r8107 d43006830429f16fcb194885140f894b5ad43520.
-- Detected Java(TM) Runtime Environment '1.8.0_102' (from '/home/qianliu/exomeSof        tware/java/jdk1.8.0_102/bin/java -Xmx1G').
-- Detected 12 CPUs and 95 gigabytes of memory.
-- Detected Sun Grid Engine in '/opt/gridengine/default'.
-- Grid engine disabled per useGrid=false option.
--
-- Run   3 jobs concurrently using    8 GB and   4 CPUs for stage 'meryl'.
-- Run   1 job  concurrently using    6 GB and  12 CPUs for stage 'mhap (cor)'.
-- Run   2 jobs concurrently using    8 GB and   6 CPUs for stage 'overlapper (obt        )'.
-- Run   2 jobs concurrently using    8 GB and   6 CPUs for stage 'overlapper (utg        )'.
-- Run   6 jobs concurrently using   15 GB and   2 CPUs for stage 'falcon_sense'.
-- Run  12 jobs concurrently using    4 GB and   1 CPU  for stage 'ovStore bucketi        zer'.
-- Run  12 jobs concurrently using    8 GB and   1 CPU  for stage 'ovStore sorting        '.
-- Run   3 jobs concurrently using    2 GB and   4 CPUs for stage 'read error dete        ction'.
-- Run  12 jobs concurrently using    1 GB and   1 CPU  for stage 'overlap error a        djustment'.
-- Run   3 jobs concurrently using   16 GB and   4 CPUs for stage 'bogart'.
-- Run   3 jobs concurrently using   31 GB and   4 CPUs for stage 'consensus'.
--
-- Generating assembly 'ecoli' in '/home/qianliu/project/assembly/ecoli-canu'
--
-- Parameters:
--
--  genomeSize        4800000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.0450 (  4.50%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0450 (  4.50%)
--
--
-- BEGIN CORRECTION
--
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting concurrent execution on Wed Feb 22 15:02:05 2017 with 25126.578 GB fre        e disk space (1 processes; 3 concurrently)

    cd correction/0-mercounts
    ./meryl.sh 1 > ./meryl.000001.out 2>&1

-- Finished on Wed Feb 22 15:02:25 2017 (20 seconds) with 25147.174 GB free disk s        pace
----------------------------------------
-- Meryl finished successfully.
-- Finished stage 'merylCheck', reset canuIteration.
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
-- For mhap overlapping, set repeat k-mer threshold to 1157.
--
-- Found 115711421 16-mers; 89186744 distinct and 77230204 unique.  Largest count         37954.
-- Finished stage 'cor-meryl', reset canuIteration.
--
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=high based on read coverage of 24.
--
-- PARAMETERS: hashes=768, minMatches=2, threshold=0.73
--
-- Given 6 GB, can fit 9000 reads per block.
-- For 3 blocks, set stride to 2 blocks.
-- Logging partitioning to 'correction/1-overlapper/partitioning.log'.
-- Configured 2 mhap precompute jobs.
-- Configured 2 mhap overlap jobs.
-- Finished stage 'cor-mhapConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting concurrent execution on Wed Feb 22 15:02:27 2017 with 25147.511 GB fre        e disk space (2 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1

-- Finished on Wed Feb 22 15:09:46 2017 (439 seconds) with 25130.143 GB free disk         space
----------------------------------------
-- All 2 mhap precompute jobs finished successfully.
-- Finished stage 'cor-mhapPrecomputeCheck', reset canuIteration.
--
**-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting concurrent execution on Wed Feb 22 15:09:46 2017 with 25130.143 GB fre        e disk space (2 processes; 1 concurrently)

    cd correction/1-overlapper
    ./mhap.sh 1 > ./mhap.000001.out 2>&1
    ./mhap.sh 2 > ./mhap.000002.out 2>&1

-- Finished on Wed Feb 22 15:10:02 2017 (16 seconds) with 25130.055 GB free disk s        pace
----------------------------------------
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting concurrent execution on Wed Feb 22 15:10:02 2017 with 25130.055 GB fre        e disk space (1 processes; 1 concurrently)

    cd correction/1-overlapper
    ./mhap.sh 1 > ./mhap.000001.out 2>&1

-- Finished on Wed Feb 22 15:10:12 2017 (10 seconds) with 25130 GB free disk space
----------------------------------------
--
-- 1 mhap jobs failed:
--   job 1-overlapper/results/000001.ovb FAILED.
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'canu iteration count too high, stopping pipeline (most likely a         problem in the grid-based computes)'.
```

**Comment by skoren** [comment]
Can you upload or paste the output in ```mhap.000001.out```?

**Comment by liuqianhn** [comment]
Hi skoren,

Thanks for your reply. I found the output in mhap.000001.out below. It seems that there is a memory issue. I have set "-Xmx1G" in the running commands. How to fix the issue below? Thanks. 
```
Running job 1 based on command line options.
Fetch blocks/000002.dat

Running block 000001 in query 000001

Picked up _JAVA_OPTIONS:  -Xmx1G
Running with these settings:
--filter-threshold = 5.0E-6
--help = false
--max-shift = 0.2
--min-olap-length = 116
--min-store-length = 0
--no-rc = false
--no-self = false
--no-tf = false
--num-hashes = 768
--num-min-matches = 2
--num-threads = 16
--ordered-kmer-size = 12
--ordered-sketch-size = 1536
--repeat-idf-scale = 10.0
--repeat-weight = 0.9
--settings = 0
--store-full-id = false
--supress-noise = 0
--threshold = 0.73
--version = false
-f = ../0-mercounts/ecoli.ms16.frequentMers.ignore.gz
-h = false
-k = 16
-p =
-q = queries/000001
-s = ./blocks/000001.dat

Reading in filter file ../0-mercounts/ecoli.ms16.frequentMers.ignore.gz.
Time (s) to read filter file: 0.165915214
Read in k-mer filter for sizes: [16]
Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
   at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.<init>(Int2ObjectOpenHashMap.java:125)
   at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.<init>(Int2ObjectOpenHashMap.java:136)
   at edu.umd.marbl.mhap.impl.MinHashSearch.<init>(MinHashSearch.java:89)
   at edu.umd.marbl.mhap.main.MhapMain.getMatchSearch(MhapMain.java:556)
   at edu.umd.marbl.mhap.main.MhapMain.computeMain(MhapMain.java:460)
   at edu.umd.marbl.mhap.main.MhapMain.main(MhapMain.java:315)
```

**Comment by brianwalenz** [comment]
Don't set the java memory size.  In this case, mhap is needing to use 6gb (reported near the top of your first output: "Run   1 job  concurrently using    6 GB and  12 CPUs for stage 'mhap (cor)'").  Canu will take care of setting this for you.

**Comment by liuqianhn** [comment]
Hi brianwalenz, Thanks for your help. I have fixed the issues. Thanks.
