### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by liuqianhn** [marbl/canu#572]
Hi I am learning how to use canu with `Canu release v1.5`. I obtained an error below in `correction/1-overlapper/mhap.*.out`. I understand that it is OutOfMemoryError in java. I am wondering that in canu, how to set the memory used by java in canu. Thank you very much. 

The major java command in canu is `java -d64 -server -Xmx6144m -jar  $bin/mhap-2.1.2.jar --repeat-weight 0.9 --repeat-idf-scale 10 -k 16 --num-hashes 256 --num-min-matches 3 --threshold 0.85 --filter-threshold 0.000005 --ordered-sketch-size 1000 --ordered-kmer-size 14 --num-threads 16`. By the way, may I know whether my understanding (below) of the parameters is correct? (1) `--num-threads 16` indicates there are 16 threads in this process, (2) `-Xmx6144m` is for this process not for a thread in the process. Could you please suggest whether I am right? Thank you.

The error is 
```
Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Exception in thread "pool-1-thread-11" Exception in thread "pool-1-thread-13" Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
        at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:83)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-13"
Exception in thread "pool-1-thread-6" Exception in thread "pool-1-thread-4" Exception in thread "pool-1-thread-16"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-12"
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-7" Exception in thread "pool-1-thread-5" Exception in thread "pool-1-thread-8" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
        at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:83)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
        at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:83)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.access$0(SequenceSketchStreamer.java:224)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$1.run(SequenceSketchStreamer.java:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" Exception in thread "pool-1-thread-9" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at edu.umd.marbl.mhap.sketch.BottomOverlapSketch.fromByteStream(BottomOverlapSketch.java:374)
        at edu.umd.marbl.mhap.impl.SequenceSketch.fromByteStream(SequenceSketch.java:83)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.readFromBinary(SequenceSketchStreamer.java:316)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:160)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.access$0(SequenceSketchStreamer.java:224)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$1.run(SequenceSketchStreamer.java:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-2" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-3" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-15" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-14" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-10" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by brianwalenz** [comment]
I've never seen this error before.  Java decided it is spending all its time managing memory and not computing, so it gave up.  The advice I found is to increase the memory limit.  Canu option mhapMemory=12g will increase the memory used for this process to 12gb.

What are you trying to assemble?  What's the expected genome size and coverage in the reads?

**Comment by liuqianhn** [comment]
Hi Brian,

Thank you very much for your prompt reply. I am trying to assembly a small genome lambda with the expected genome size 50k. The coverage is thus higher than 500X. 

I will try to increase mhapMemory to see whether the issue would occur again. Thanks.

**Comment by brianwalenz** [comment]
500x is just way too much data.  50x of raw reads is reasonable for small simple genomes.  Canu only assembles the longest 40x of corrected reads anyway.

You can probably throw out everything smaller than 10kbp (minReadLength=10000), but check the read length histogram in the canu screen output to see how many reads are above that.  You'll probably then also want to set stopOnReadQuality=false to make canu not fail when most of the input reads are ignored.

**Comment by liuqianhn** [comment]
Hi Brian, Thank you very much for your suggestions. I downsampled my data to ~50X, and I can successfully run canu.

**Comment by liuqianhn** [comment]
Hi Brian, I am sorry to trouble you again. I found that I did not have any result after I finished Canu. 

I thus downloaded ecoli data in canu tutorial, and I run "canu -p ecoli -d ecoli-oxford genomeSize=4.8m -nanopore-raw oxford.fasta useGrid=false mhapMemory=30G mhapThreads=8". I always had the error below in `/correction/1-overlapper/mhap.000001.out`, although I increased `mhapMemory` from 30G to 120G. 
```
Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.<init>(Int2ObjectOpenHashMap.java:126)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.<init>(Int2ObjectOpenHashMap.java:136)
        at edu.umd.marbl.mhap.impl.MinHashSearch.<init>(MinHashSearch.java:89)
        at edu.umd.marbl.mhap.main.MhapMain.getMatchSearch(MhapMain.java:556)
        at edu.umd.marbl.mhap.main.MhapMain.computeMain(MhapMain.java:460)
        at edu.umd.marbl.mhap.main.MhapMain.main(MhapMain.java:315)
```

May I know what is wrong here? Thanks.

**Comment by brianwalenz** [comment]
What OS is this?

What `java -version`?

Are there any limits on process size?  e.g.: **max memory size**
```
$ ulimit -a
number of pseudoterminals            (-P) unlimited
socket buffer size       (bytes, -b) unlimited
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) 50331648
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 3770829
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 1048576
cpu time               (seconds, -t) unlimited
max user processes              (-u) 89999
virtual memory          (kbytes, -v) unlimited
swap size               (kbytes, -w) unlimited
```

**Comment by liuqianhn** [comment]
Hi Brian, my IO is `CentOS release 6.6 (Final)`

`Java -version` is 
```
Picked up _JAVA_OPTIONS:  -Xmx1G
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

There is no limits on `max memory size`
```
[qianliu@biocluster 1-overlapper]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1162627
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) 8000000
file locks                      (-x) unlimited
```

**Comment by liuqianhn** [comment]
Hi Brian, I changed _JAVA_OPTIONS, and could successfully run canu on ecoli and obtain the results. It seems that the setting of mhapMemory cannot change the default java setting in my computer and thus cause OutOfMemoryError. Thanks for your help.

**Comment by skoren** [comment]
I believe _JAVA_OPTIONS has higher precedence than the command line (which is what Canu is using to set the memory) which is why you had the error. Unless there is a program you use which requires _JAVA_OPTIONS to be set, I would leave it unset and use JAVA_TOOL_OPTIONS which can be overwritten by command-line.
