### ISSUE TITLE
Canu error through RepLong: canu failed with 'gatekeeper store exists, but contains no reads'

### ISSUE THREAD

**Issue by LuciaA2** [marbl/canu#840]
Hi,

I'm trying to find repeated sequences in the genome of my bacteria through RepLong, which needs to run Canu. When I execute the RepLong command in Linux, it starts to run until the following error appears:

```
=============================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'gatekeeper store exists, but contains no reads'.

temp/correction/1-overlapper/001/*.ovb
ERROR:  invalid arg 'temp/correction/1-overlapper/001/*.ovb'
usage: /home/carlos/Escritorio/Lucia/replong-master/canu-1.4/Linux-amd64/bin/overlapConvert [options] file.ovb[.gz]

  -G             gkpStore (needed for -coords, the default)

  -coords        output coordiantes on reads
  -hangs         output hangs on reads
  -raw           output raw hangs on reads

  -native        input ovb file is NOT snappy compressed

ERROR:  no overlap files supplied
filter overlap file to merge repeat
Traceback (most recent call last):
  File "/home/carlos/Escritorio/Lucia/replong-master/edge_1.py", line 87, in <module>
    outfilename)
  File "/home/carlos/Escritorio/Lucia/replong-master/edge_1.py", line 9, in buildEdgeWithFrom
    with open(overlapfile, 'r') as a, open(readlengthfile, 'r') as b,\
IOError: [Errno 2] No such file or directory: 'temp/correction/step2.gkpStore/reads.txt'
use community detection to merge repeat
```
Thank you very much,

Lucía

**Comment by skoren** [comment]
I am not sure how RepLong is using Canu. It seems that there are a bunch of errors with RepLong's canu run but without known what command is run we can't help. Have you tried contacting the RepLong authors?
